### ISSUE TITLE
Make the tabs navigable with the tab key

### ISSUE THREAD

**Issue by MalinSvenberg** [graasp/graasp-app-code-capsule#110]
Right now it's not possible to go between the different tabs using the tab key. 

<img width="808" alt="Screenshot 2023-05-03 at 14 34 44" src="https://user-images.githubusercontent.com/56155987/235917518-9d0c7e11-2495-4c99-9b71-7f8dba735b2e.png">

**Comment by spaenleh** [comment]
It works but the iframe needs to be selected.
